# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zVuqPMfS5K_r95HGmA4YY2pVOQv1PNi
"""

print("=" * 40)
print("   HOSPITAL PATIENT REGISTRATION FORM")
print("=" * 40)

# Patient's Name
name = input("\nPatient's Full Name: ")

# Date of Birth
dob = input("Date of Birth (DD/MM/YYYY): ")

# Gender
print("\nGender:")
print("1. Male")
print("2. Female")
print("3. Other")
gender_choice = input("Enter choice (1/2/3): ")

if gender_choice == "1":
    gender = "Male"
elif gender_choice == "2":
    gender = "Female"
else:
    gender = "Other"

# Marital Status
print("\nMarital Status:")
print("1. Single")
print("2. Married")
print("3. Divorced")
print("4. Widowed")
marital_choice = input("Enter choice (1/2/3/4): ")

if marital_choice == "1":
    marital_status = "Single"
elif marital_choice == "2":
    marital_status = "Married"
elif marital_choice == "3":
    marital_status = "Divorced"
else:
    marital_status = "Widowed"

# Insurance Details
insurance_provider = input("\nInsurance Provider Name: ")
policy_number = input("Policy Number: ")

# Display Summary
print("\n" + "=" * 40)
print("       REGISTRATION SUMMARY")
print("=" * 40)
print(f"Patient's Name     : {name}")
print(f"Date of Birth      : {dob}")
print(f"Gender             : {gender}")
print(f"Marital Status     : {marital_status}")
print(f"Insurance Provider : {insurance_provider}")
print(f"Policy Number      : {policy_number}")
print("=" * 40)
print("Registration Successful!")

print("=" * 40)
print("      COLLEGE ADMISSION FORM")
print("=" * 40)

# Student's Name
name = input("\nStudent's Full Name: ")

# Date of Birth
dob = input("Date of Birth (DD/MM/YYYY): ")

# Gender
print("\nGender:")
print("1. Male")
print("2. Female")
print("3. Other")
gender_choice = input("Enter choice (1/2/3): ")

if gender_choice == "1":
    gender = "Male"
elif gender_choice == "2":
    gender = "Female"
else:
    gender = "Other"

# Contact Details
print("\n-- Contact Details --")
phone = input("Phone Number: ")
email = input("Email Address: ")
address = input("Home Address: ")

# High School Information
print("\n-- High School Information --")
school_name = input("Name of High School: ")
graduation_date = input("Graduation Date (MM/YYYY): ")

# GPA
gpa = input("\nHigh School GPA (e.g. 3.8 / 4.0): ")

# Standardized Test Scores
print("\n-- Standardized Test Scores --")
print("1. SAT")
print("2. ACT")
print("3. Both")
print("4. None")
test_choice = input("Which test(s) did you take? (1/2/3/4): ")

sat_score = "N/A"
act_score = "N/A"

if test_choice == "1":
    sat_score = input("SAT Score (out of 1600): ")
elif test_choice == "2":
    act_score = input("ACT Score (out of 36): ")
elif test_choice == "3":
    sat_score = input("SAT Score (out of 1600): ")
    act_score = input("ACT Score (out of 36): ")

# Certification Signature
print("\n-- Certification & Signature --")
print("By entering your full name below, you digitally certify that")
print("all information provided in this form is accurate and authentic.")
signature = input("\nType your full name as your digital signature: ")

import datetime
signed_date = datetime.datetime.now().strftime("%d/%m/%Y %I:%M %p")

# Display Summary
print("\n" + "=" * 45)
print("         ADMISSION FORM SUMMARY")
print("=" * 45)
print(f"Student's Name     : {name}")
print(f"Date of Birth      : {dob}")
print(f"Gender             : {gender}")

print("\n-- Contact Details --")
print(f"Phone Number       : {phone}")
print(f"Email Address      : {email}")
print(f"Home Address       : {address}")

print("\n-- High School Information --")
print(f"Name of School     : {school_name}")
print(f"Graduation Date    : {graduation_date}")
print(f"GPA                : {gpa}")

print("\n-- Standardized Test Scores --")
print(f"SAT Score          : {sat_score}")
print(f"ACT Score          : {act_score}")

print("\n-- Certification & Signature --")
print(f"Digital Signature  : {signature}")
print(f"Date & Time Signed : {signed_date}")
print("=" * 45)
print("✅ Form Submitted Successfully!")

import datetime

print("=" * 50)
print("         GYM MEMBERSHIP REGISTRATION FORM")
print("=" * 50)

# ── Personal Information ──────────────────────────
name = input("\nFull Name: ")
dob = input("Date of Birth (DD/MM/YYYY): ")

print("\nGender:")
print("1. Male")
print("2. Female")
print("3. Other")
gender_choice = input("Enter choice (1/2/3): ")
if gender_choice == "1":
    gender = "Male"
elif gender_choice == "2":
    gender = "Female"
else:
    gender = "Other"

# ── Contact Details ───────────────────────────────
print("\n-- Contact Details --")
phone   = input("Phone Number: ")
email   = input("Email Address: ")
address = input("Home Address: ")

# ── Membership Type ───────────────────────────────
print("\n-- Membership Tier --")
print("1. Basic")
print("2. Premium")
print("3. VIP")
tier_choice = input("Select your membership tier (1/2/3): ")
if tier_choice == "1":
    tier = "Basic"
elif tier_choice == "2":
    tier = "Premium"
else:
    tier = "VIP"

print("\n-- Membership Duration --")
print("1. Monthly")
print("2. Annual")
print("3. Paid-in-Full")
duration_choice = input("Select your membership duration (1/2/3): ")
if duration_choice == "1":
    duration = "Monthly"
elif duration_choice == "2":
    duration = "Annual"
else:
    duration = "Paid-in-Full"

# ── Add-ons ───────────────────────────────────────
print("\n-- Add-ons (enter Y for Yes, N for No) --")
locker    = input("Locker Rental:               ").strip().upper()
training  = input("Personal Training Package:   ").strip().upper()
towel     = input("Towel Service:               ").strip().upper()

locker_status   = "Yes" if locker   == "Y" else "No"
training_status = "Yes" if training == "Y" else "No"
towel_status    = "Yes" if towel    == "Y" else "No"

# ── Start Date ────────────────────────────────────
start_date = input("\nMembership Start Date (DD/MM/YYYY): ")

# ── Waiver of Liability ───────────────────────────
print("\n" + "=" * 50)
print("            WAIVER OF LIABILITY")
print("=" * 50)
print("""
By signing this form, I acknowledge and agree that:

1. Physical exercise involves inherent risks, including
   but not limited to bodily injury, muscle strain,
   cardiac events, or accidents.

2. I voluntarily assume all risks associated with my
   participation in gym activities and use of equipment.

3. I release the gym, its staff, and management from
   any liability for injuries or damages arising from
   my use of the facilities.

4. I confirm that I am medically fit to engage in
   physical exercise and have consulted a physician
   if necessary.
""")
waiver_agree = input("Do you agree to the Waiver of Liability? (Y/N): ").strip().upper()
waiver_status = "Agreed" if waiver_agree == "Y" else "Not Agreed"

# ── Gym Rules Acknowledgment ──────────────────────
print("\n" + "=" * 50)
print("          GYM RULES ACKNOWLEDGMENT")
print("=" * 50)
print("""
By signing below, I confirm that I have read and will
follow all gym policies, including:

1. ATTIRE     : Appropriate workout clothing and
                closed-toe shoes must be worn at all
                times on the gym floor.

2. HYGIENE    : Members must wipe down equipment
                after use and maintain personal hygiene
                while using shared facilities.

3. RE-RACKING : All weights, dumbbells, and barbells
                must be returned to their designated
                racks after use.

4. CONDUCT    : Respectful behavior toward staff and
                fellow members is required at all times.
""")
rules_agree = input("Do you agree to follow the Gym Rules? (Y/N): ").strip().upper()
rules_status = "Agreed" if rules_agree == "Y" else "Not Agreed"

# ── Digital Signature ─────────────────────────────
print("\n-- Certification & Signature --")
print("By entering your full name below, you digitally certify")
print("that all information provided is accurate and authentic.")
signature   = input("\nType your full name as your digital signature: ")
signed_date = datetime.datetime.now().strftime("%d/%m/%Y %I:%M %p")

# ── Summary ───────────────────────────────────────
print("\n" + "=" * 50)
print("         REGISTRATION SUMMARY")
print("=" * 50)
print(f"Full Name          : {name}")
print(f"Date of Birth      : {dob}")
print(f"Gender             : {gender}")

print("\n-- Contact Details --")
print(f"Phone Number       : {phone}")
print(f"Email Address      : {email}")
print(f"Home Address       : {address}")

print("\n-- Membership --")
print(f"Tier               : {tier}")
print(f"Duration           : {duration}")
print(f"Start Date         : {start_date}")

print("\n-- Add-ons --")
print(f"Locker Rental      : {locker_status}")
print(f"Personal Training  : {training_status}")
print(f"Towel Service      : {towel_status}")

print("\n-- Agreements --")
print(f"Waiver of Liability: {waiver_status}")
print(f"Gym Rules          : {rules_status}")

print("\n-- Certification & Signature --")
print(f"Digital Signature  : {signature}")
print(f"Date & Time Signed : {signed_date}")
print("=" * 50)
print("✅ Registration Submitted Successfully!")

import datetime

print("=" * 50)
print("        EMPLOYEE REGISTRATION FORM")
print("=" * 50)

# ── Personal Information ──────────────────────────
print("\n-- Personal Information --")
name = input("Full Name: ")
dob = input("Date of Birth (DD/MM/YYYY): ")

print("\nGender:")
print("1. Male")
print("2. Female")
print("3. Other")
gender_choice = input("Enter choice (1/2/3): ")
if gender_choice == "1":
    gender = "Male"
elif gender_choice == "2":
    gender = "Female"
else:
    gender = "Other"

print("\nMarital Status:")
print("1. Single")
print("2. Married")
print("3. Divorced")
print("4. Widowed")
marital_choice = input("Enter choice (1/2/3/4): ")
if marital_choice == "1":
    marital_status = "Single"
elif marital_choice == "2":
    marital_status = "Married"
elif marital_choice == "3":
    marital_status = "Divorced"
else:
    marital_status = "Widowed"

nationality = input("\nNationality: ")
national_id = input("National ID / Passport Number: ")

# ── Contact Details ───────────────────────────────
print("\n-- Contact Details --")
phone     = input("Phone Number: ")
email     = input("Email Address: ")
address   = input("Home Address: ")
emergency_contact_name   = input("\nEmergency Contact Name: ")
emergency_contact_phone  = input("Emergency Contact Phone: ")
emergency_contact_relation = input("Relationship to Employee: ")

# ── Job Information ───────────────────────────────
print("\n-- Job Information --")
job_title    = input("Job Title / Position: ")
department   = input("Department: ")
employee_id  = input("Employee ID: ")
start_date   = input("Employment Start Date (DD/MM/YYYY): ")

print("\nEmployment Type:")
print("1. Full-Time")
print("2. Part-Time")
print("3. Contract")
print("4. Internship")
emp_type_choice = input("Enter choice (1/2/3/4): ")
if emp_type_choice == "1":
    employment_type = "Full-Time"
elif emp_type_choice == "2":
    employment_type = "Part-Time"
elif emp_type_choice == "3":
    employment_type = "Contract"
else:
    employment_type = "Internship"

print("\nWork Mode:")
print("1. On-Site")
print("2. Remote")
print("3. Hybrid")
work_mode_choice = input("Enter choice (1/2/3): ")
if work_mode_choice == "1":
    work_mode = "On-Site"
elif work_mode_choice == "2":
    work_mode = "Remote"
else:
    work_mode = "Hybrid"

supervisor = input("\nDirect Supervisor / Manager Name: ")

# ── Educational Background ────────────────────────
print("\n-- Educational Background --")
highest_qualification = input("Highest Qualification (e.g. Bachelor's, Master's): ")
field_of_study        = input("Field of Study: ")
institution           = input("Institution Name: ")
graduation_year       = input("Year of Graduation: ")

# ── Work Experience ───────────────────────────────
print("\n-- Previous Work Experience --")
prev_employer  = input("Previous Employer (type 'N/A' if none): ")
prev_job_title = input("Previous Job Title: ")
prev_years     = input("Years of Experience: ")

# ── Bank & Payroll Information ────────────────────
print("\n-- Bank & Payroll Information --")
bank_name      = input("Bank Name: ")
account_number = input("Bank Account Number: ")
account_name   = input("Account Holder Name: ")

print("\nPayment Frequency:")
print("1. Weekly")
print("2. Bi-Weekly")
print("3. Monthly")
pay_choice = input("Enter choice (1/2/3): ")
if pay_choice == "1":
    pay_frequency = "Weekly"
elif pay_choice == "2":
    pay_frequency = "Bi-Weekly"
else:
    pay_frequency = "Monthly"

# ── IT & System Access ────────────────────────────
print("\n-- IT & System Access (Y for Yes, N for No) --")
laptop      = input("Company Laptop Required:        ").strip().upper()
email_acc   = input("Company Email Account Required: ").strip().upper()
system_acc  = input("System / Software Access Required: ").strip().upper()

laptop_status     = "Yes" if laptop     == "Y" else "No"
email_acc_status  = "Yes" if email_acc  == "Y" else "No"
system_acc_status = "Yes" if system_acc == "Y" else "No"

# ── Code of Conduct ───────────────────────────────
print("\n" + "=" * 50)
print("           CODE OF CONDUCT")
print("=" * 50)
print("""
By signing this form, I acknowledge and agree to:

1. PROFESSIONALISM : Maintain respectful and ethical
                     conduct toward all colleagues,
                     clients, and stakeholders.

2. CONFIDENTIALITY : Protect all sensitive company
                     and client information at all
                     times.

3. ATTENDANCE      : Adhere to the company's working
                     hours and attendance policies.

4. COMPLIANCE      : Follow all company policies,
                     procedures, and applicable laws.

5. CONFLICT        : Disclose any conflicts of interest
                     to management immediately.
""")
conduct_agree = input("Do you agree to the Code of Conduct? (Y/N): ").strip().upper()
conduct_status = "Agreed" if conduct_agree == "Y" else "Not Agreed"

# ── Digital Signature ─────────────────────────────
print("\n-- Certification & Signature --")
print("By entering your full name below, you certify that")
print("all information provided is accurate and authentic.")
signature   = input("\nType your full name as your digital signature: ")
signed_date = datetime.datetime.now().strftime("%d/%m/%Y %I:%M %p")

# ── Summary ───────────────────────────────────────
print("\n" + "=" * 50)
print("          REGISTRATION SUMMARY")
print("=" * 50)

print("\n-- Personal Information --")
print(f"Full Name              : {name}")
print(f"Date of Birth          : {dob}")
print(f"Gender                 : {gender}")
print(f"Marital Status         : {marital_status}")
print(f"Nationality            : {nationality}")
print(f"National ID / Passport : {national_id}")

print("\n-- Contact Details --")
print(f"Phone Number           : {phone}")
print(f"Email Address          : {email}")
print(f"Home Address           : {address}")
print(f"Emergency Contact      : {emergency_contact_name} ({emergency_contact_relation})")
print(f"Emergency Phone        : {emergency_contact_phone}")

print("\n-- Job Information --")
print(f"Job Title              : {job_title}")
print(f"Department             : {department}")
print(f"Employee ID            : {employee_id}")
print(f"Employment Type        : {employment_type}")
print(f"Work Mode              : {work_mode}")
print(f"Start Date             : {start_date}")
print(f"Supervisor             : {supervisor}")

print("\n-- Educational Background --")
print(f"Highest Qualification  : {highest_qualification}")
print(f"Field of Study         : {field_of_study}")
print(f"Institution            : {institution}")
print(f"Graduation Year        : {graduation_year}")

print("\n-- Previous Work Experience --")
print(f"Previous Employer      : {prev_employer}")
print(f"Previous Job Title     : {prev_job_title}")
print(f"Years of Experience    : {prev_years}")

print("\n-- Bank & Payroll Information --")
print(f"Bank Name              : {bank_name}")
print(f"Account Number         : {account_number}")
print(f"Account Holder Name    : {account_name}")
print(f"Payment Frequency      : {pay_frequency}")

print("\n-- IT & System Access --")
print(f"Company Laptop         : {laptop_status}")
print(f"Company Email          : {email_acc_status}")
print(f"System Access          : {system_acc_status}")

print("\n-- Agreements --")
print(f"Code of Conduct        : {conduct_status}")

print("\n-- Certification & Signature --")
print(f"Digital Signature      : {signature}")
print(f"Date & Time Signed     : {signed_date}")
print("=" * 50)
print("✅ Employee Registration Submitted Successfully!")

import datetime

print("=" * 45)
print("      BANK ACCOUNT REGISTRATION FORM")
print("=" * 45)

# ── Personal Information ──────────────────────────
print("\n-- Personal Information --")
name = input("Full Name: ")
dob  = input("Date of Birth (DD/MM/YYYY): ")

print("\nGender:")
print("1. Male")
print("2. Female")
print("3. Other")
gender_choice = input("Enter choice (1/2/3): ")
if gender_choice == "1":
    gender = "Male"
elif gender_choice == "2":
    gender = "Female"
else:
    gender = "Other"

nationality = input("\nNationality: ")
national_id = input("National ID / Passport Number: ")

# ── Contact Details ───────────────────────────────
print("\n-- Contact Details --")
phone   = input("Phone Number: ")
email   = input("Email Address: ")
address = input("Home Address: ")

# ── Account Information ───────────────────────────
print("\n-- Account Information --")

print("\nAccount Type:")
print("1. Savings Account")
print("2. Checking / Current Account")
acc_choice = input("Enter choice (1/2): ")
if acc_choice == "1":
    account_type = "Savings Account"
else:
    account_type = "Checking / Current Account"

initial_deposit = input("\nInitial Deposit Amount: $")

# ── Identity Verification ─────────────────────────
print("\n-- Identity Verification --")
print("\nID Type Submitted:")
print("1. National ID Card")
print("2. Passport")
print("3. Driver's License")
id_choice = input("Enter choice (1/2/3): ")
if id_choice == "1":
    id_type = "National ID Card"
elif id_choice == "2":
    id_type = "Passport"
else:
    id_type = "Driver's License"

id_number = input("ID Number: ")

# ── Terms & Conditions ────────────────────────────
print("\n" + "=" * 45)
print("         TERMS & CONDITIONS")
print("=" * 45)
print("""
By signing this form, I agree that:

1. All information provided is true and accurate.
2. I will keep my account credentials secure.
3. I will notify the bank of any changes to
   my personal information.
4. I will comply with all banking policies
   and regulations.
""")
terms_agree  = input("Do you agree to the Terms & Conditions? (Y/N): ").strip().upper()
terms_status = "Agreed" if terms_agree == "Y" else "Not Agreed"

# ── Digital Signature ─────────────────────────────
print("\n-- Signature --")
signature   = input("Type your full name as your digital signature: ")
signed_date = datetime.datetime.now().strftime("%d/%m/%Y %I:%M %p")

# ── Summary ───────────────────────────────────────
print("\n" + "=" * 45)
print("          REGISTRATION SUMMARY")
print("=" * 45)

print("\n-- Personal Information --")
print(f"Full Name        : {name}")
print(f"Date of Birth    : {dob}")
print(f"Gender           : {gender}")
print(f"Nationality      : {nationality}")
print(f"National ID      : {national_id}")

print("\n-- Contact Details --")
print(f"Phone Number     : {phone}")
print(f"Email Address    : {email}")
print(f"Home Address     : {address}")

print("\n-- Account Information --")
print(f"Account Type     : {account_type}")
print(f"Initial Deposit  : ${initial_deposit}")

print("\n-- Identity Verification --")
print(f"ID Type          : {id_type}")
print(f"ID Number        : {id_number}")

print("\n-- Agreement --")
print(f"Terms & Conditions : {terms_status}")

print("\n-- Signature --")
print(f"Digital Signature  : {signature}")
print(f"Date & Time Signed : {signed_date}")
print("=" * 45)
print("✅ Bank Account Registration Submitted Successfully!")