# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xKWBW-opTpFh7jchuK6e7ZwHalQeEmIo
"""



print("Personal Profile")
print(input("Name:"))
print(input("City:"))
print(input("College:"))
print(input("Dreamcompany:"))